---
- name: install 'ntp' package
  package:
    name: 
      - "{{ ntp_package_name }}"
      
- name: Start 'ntp' Service    
  service:
    name: "{{ ntp_package_name }}"
    enabled: yes
    state: started